### ISSUE TITLE
Certificate is not renewed during runtime, but after restart it got renewed

### ISSUE THREAD

**Issue by korney4eg** [nginx-le/nginx-le#41]
Hello,

I see the strange behavior of le bot. After some time after generating new certificate I got following logs:
```log
nginx-le | trying to update letsencrypt ...
nginx-le | letsencrypt certificate will expire soon or missing, renewing...
nginx-le | Saving debug log to /var/log/letsencrypt/letsencrypt.log
nginx-le | Plugins selected: Authenticator webroot, Installer None
nginx-le | Renewing an existing certificate
nginx-le | Performing the following challenges:
nginx-le | http-01 challenge for blog.makvaz.com
nginx-le | http-01 challenge for bw.makvaz.com
nginx-le | http-01 challenge for makvaz.com
nginx-le | http-01 challenge for notes.makvaz.com
nginx-le | http-01 challenge for vervedea.com
nginx-le | http-01 challenge for www.vervedea.com
nginx-le | http-01 challenge for zametki.makvaz.com
nginx-le | Using the webroot path /usr/share/nginx/html for all unmatched domains.
nginx-le | Waiting for verification...
nginx-le | Challenge failed for domain blog.makvaz.com
nginx-le | Challenge failed for domain bw.makvaz.com
nginx-le | Challenge failed for domain makvaz.com
nginx-le | Challenge failed for domain notes.makvaz.com
nginx-le | Challenge failed for domain vervedea.com
nginx-le | Challenge failed for domain www.vervedea.com
nginx-le | Challenge failed for domain zametki.makvaz.com
nginx-le | http-01 challenge for blog.makvaz.com
nginx-le | http-01 challenge for bw.makvaz.com
nginx-le | http-01 challenge for makvaz.com
nginx-le | http-01 challenge for notes.makvaz.com
nginx-le | http-01 challenge for vervedea.com
nginx-le | http-01 challenge for www.vervedea.com
nginx-le | http-01 challenge for zametki.makvaz.com
nginx-le | Cleaning up challenges
nginx-le | Some challenges have failed.
nginx-le | IMPORTANT NOTES:
nginx-le | Error in atexit._run_exitfuncs:
nginx-le | Traceback (most recent call last):
nginx-le |   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
nginx-le |     func(*targs, **kargs)
nginx-le |   File "/usr/lib/python2.7/site-packages/certbot/util.py", line 598, in _atexit_call
nginx-le |     func(*args, **kwargs)
nginx-le |   File "/usr/lib/python2.7/site-packages/certbot/_internal/reporter.py", line 97, in print_messages
nginx-le |     next_wrapper.fill(line) for line in lines[1:]))
nginx-le | UnicodeEncodeError: 'ascii' codec can't encode characters in position 266-270: ordinal not in range(128)
nginx-le | Error in sys.exitfunc:
nginx-le | An unexpected error occurred:
nginx-le | UnicodeEncodeError: 'ascii' codec can't encode characters in position 266-270: ordinal not in range(128)
nginx-le |  - The following errors were reported by the server:
nginx-le | Please see the logfiles in /var/log/letsencrypt for more details.
nginx-le | failed to run certbot
nginx-le | '/etc/nginx/conf.d.disabled' -> '/etc/nginx/conf.d/conf.d.disabled'
nginx-le | reload nginx with ssl
```

So it seem cannot update certificates. But if I restart container (wanted to add more debug info) using `docker-compose restart` it successfully regenerates new cert.
```log
nginx-le | start nginx
nginx-le | ssl_key=le-key.pem, ssl_cert=le-crt.pem, ssl_chain_cert=le-chain-crt.pem
nginx-le | '/etc/nginx/service-makvaz.com.conf' -> '/etc/nginx/conf.d/service-makvaz.com.conf'
nginx-le | '/etc/nginx/service-vervedea.com.conf' -> '/etc/nginx/conf.d/service-vervedea.com.conf'
nginx-le | '/etc/nginx/conf.d' -> '/etc/nginx/conf.d.disabled'
nginx-le | start letsencrypt updater
nginx-le | trying to update letsencrypt ...
nginx-le | letsencrypt certificate will expire soon or missing, renewing...
nginx-le | Saving debug log to /var/log/letsencrypt/letsencrypt.log
nginx-le | Plugins selected: Authenticator webroot, Installer None
nginx-le | Obtaining a new certificate
nginx-le | Performing the following challenges:
nginx-le | http-01 challenge for blog.makvaz.com
nginx-le | http-01 challenge for bw.makvaz.com
nginx-le | http-01 challenge for makvaz.com
nginx-le | http-01 challenge for notes.makvaz.com
nginx-le | http-01 challenge for vervedea.com
nginx-le | http-01 challenge for www.vervedea.com
nginx-le | http-01 challenge for zametki.makvaz.com
nginx-le | Using the webroot path /usr/share/nginx/html for all unmatched domains.
nginx-le | Waiting for verification...
nginx-le | Cleaning up challenges
nginx-le | IMPORTANT NOTES:
nginx-le |  - Congratulations! Your certificate and chain have been saved at:
nginx-le |    /etc/letsencrypt/live/notes.makvaz.com/fullchain.pem
nginx-le |    Your key file has been saved at:
nginx-le |    /etc/letsencrypt/live/notes.makvaz.com/privkey.pem
nginx-le |    Your cert will expire on 2020-11-01. To obtain a new or tweaked
nginx-le |    version of this certificate in the future, simply run certbot
nginx-le |    again. To non-interactively renew *all* of your certificates, run
nginx-le |    "certbot renew"
nginx-le |  - Your account credentials have been saved in your Certbot
nginx-le |    configuration directory at /etc/letsencrypt. You should make a
nginx-le |    secure backup of this folder now. This configuration directory will
nginx-le |    also contain certificates and private keys obtained by Certbot so
nginx-le |    making regular backups of this folder is ideal.
nginx-le |  - If you like Certbot, please consider supporting our work by:
nginx-le |
nginx-le |    Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
nginx-le |    Donating to EFF:                    https://eff.org/donate-le
nginx-le |
nginx-le | '/etc/letsencrypt/live/notes.makvaz.com/privkey.pem' -> '/etc/nginx/ssl/le-key.pem'
nginx-le | '/etc/letsencrypt/live/notes.makvaz.com/fullchain.pem' -> '/etc/nginx/ssl/le-crt.pem'
nginx-le | '/etc/letsencrypt/live/notes.makvaz.com/chain.pem' -> '/etc/nginx/ssl/le-chain-crt.pem'
nginx-le | '/etc/nginx/conf.d.disabled' -> '/etc/nginx/conf.d'
nginx-le | reload nginx with ssl
```

Here is my docker-compose file:
```yaml
version: '2'
services:
    nginx:
        build: .
        image: umputun/nginx-le:latest
        restart: always
        container_name: nginx-le
        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./etc/ssl:/etc/nginx/ssl
            - /var/log/nginx:/var/log/nginx
            - /etc/nginx/sites-enabled/makvaz.com:/etc/nginx/service-makvaz.com.conf
            - /opt/sites/makvaz.com:/srv/makvaz.com
            - /etc/nginx/sites-enabled/vervedea.com:/etc/nginx/service-vervedea.com.conf
            - /opt/sites/vervedea:/srv/vervedea.com
        ports:
            - "443:443"
            - "80:80"
        environment:
            - TZ=UTC
            - LETSENCRYPT=true
            - LE_EMAIL=korneevayu@gmail.com
            - LE_FQDN=notes.makvaz.com,zametki.makvaz.com,blog.makvaz.com,bw.makvaz.com,makvaz.com,www.vervedea.com,vervedea.com
            - SSL_CERT=le-crt.pem
            - SSL_KEY=le-key.pem
            - SSL_CHAIN_CERT=le-chain-crt.pem
        networks:
            - common_web
networks:
  common_web:
    external: true
```

Using version https://github.com/nginx-le/nginx-le/commit/261afe71a9b729cbd388a52348c5b48261cc9d48

Am I missing anything here?

Thank you for great product.
