### ISSUE TITLE
failed to run certbot

### ISSUE THREAD

**Issue by lzrdblzzrd** [nginx-le/nginx-le#61]
I don't understand why this error can be.

```
start nginx
ssl_key=le-key.pem, ssl_cert=le-crt.pem, ssl_chain_cert=le-chain-crt.pem
cp: can't stat '/etc/nginx/conf.d-le/*.conf': No such file or directory
cp: can't stat '/etc/nginx/stream.conf.d-le/*.conf': No such file or directory
'/etc/nginx/conf.d' -> '/etc/nginx/conf.d.disabled'
'/etc/nginx/stream.d' -> '/etc/nginx/stream.d.disabled'
start letsencrypt updater
trying to update letsencrypt ...
letsencrypt certificate will expire soon or missing, renewing...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for www.*my.domain*
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: www.*my.domain*
  Type:   connection
  Detail: 176.*my.ip*.107: Fetching http://www.*my.domain*/.well-known/acme-challenge/FoenBak6jY93v4e88oM_jbJr5lV7zP3RfQBL6JZk6dg: Timeout during connect (likely firewall problem)
Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
failed to run certbot
'/etc/nginx/conf.d.disabled' -> '/etc/nginx/conf.d'
'/etc/nginx/stream.d.disabled' -> '/etc/nginx/stream.d'
reload nginx with ssl
2022/05/18 17:50:15 [notice] 35#35: signal process started
```

**Comment by umputun** [comment]
pls add the configuration you used, i.e. your docker-compose (or docker command line) and nginx service config.

**Comment by lzrdblzzrd** [comment]
I don't know where I can find the nginx service config (if nginx.conf is meant, then the standard config file from image is used), but here are the contents of docker-compose.yml, I just changed some parameters to fit my data:

```
version: '2'
services:

    nginx:
        build: .
        image: umputun/nginx-le:latest
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - /home/lzrdblzzrd/Documents/nginx-le/etc/ssl:/etc/nginx/ssl
            - /home/lzrdblzzrd/Documents/nginx-le/etc/nginx/service.conf:/etc/nginx/service.conf
            # - ./etc/service-example-2.conf:/etc/nginx/service2.conf # more services, should be service*.conf
            # - ./etc/stream-example-2.conf:/etc/nginx/stream2.conf # more streams, should be stream*.conf
            # - ./etc/conf.d:/etc/nginx/conf.d-le # configuration folder, all files from it will be added
            # - ./etc/stream.conf:/etc/nginx/stream.conf.d-le # streams configuration folder, all files from it will be added
        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=UTC
            - LETSENCRYPT=true
            - LE_EMAIL=lzrdblzzrd@my.email
            - LE_FQDN=www.my.domain
            #- SSL_CERT=le-crt.pem
            #- SSL_KEY=le-key.pem
            #- SSL_CHAIN_CERT=le-chain-crt.pem
```
